version: '3.8'
services:

  db_services:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - micros-net
    restart: always

  redis:
    image: redis:latest
    container_name: redis_auth
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - micros-net

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8085:8080"
    networks:
      - micros-net
    restart: always
    volumes:
      - pulsar_data:/pulsar/data
    environment:
      - PULSAR_STANDALONE_USE_SCHEMA_REGISTRY=true
    
  create_namespace_topic:
    image: apachepulsar/pulsar:latest
    container_name: create_namespace_topic
    depends_on:
      - pulsar
    networks:
      - micros-net
    # Este contenedor se queda en segundo plano un momento, usa pulsar-admin para crear namespace y tópico
    command: >
      sh -c "
        echo 'Esperando que Pulsar esté listo...';
        for i in 1 2 3 4 5; do
          bin/pulsar-admin clusters list && break || (echo 'Aún no listo'; sleep 5);
        done;
        echo 'Creando namespace public/default...';
        bin/pulsar-admin namespaces create public/default || echo 'Ya existe';
        echo 'Creando tópico persistent://public/default/event-user...';
        bin/pulsar-admin topics create persistent://public/default/event-user || echo 'Ya existe';
        echo 'Listo. Saliendo.'
      "
    restart: "no"   # Solo queremos que ejecute una vez y termine

  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:5000"
    restart: always
    networks:
      - micros-net
    depends_on:
      - db_services
      - pulsar
      - create_namespace_topic

  auth_service:
    build: ./auth_service
    ports:
      - "8081:5001"
    restart: always
    networks:
      - micros-net
    depends_on:
      - db_services
      - pulsar
      - create_namespace_topic
    environment:
      - ENCRYPTION_KEY=7d0X4l7ZJPCoD1qHVp35u-AwevhjVW0CiSMuWx9waBM=


  certificator_service:
    build: ./certificator_service
    ports:
      - "8082:5002"
    restart: always
    networks:
      - micros-net
    depends_on:
      - db_services
      - pulsar
      - create_namespace_topic
      

  item_valor_service:
    build: ./item_valor_service
    ports:
      - "8083:5003"
    restart: always
    networks:
      - micros-net
    depends_on:
      - db_services
      - pulsar
      - create_namespace_topic
      
    environment:
      - ENCRYPTION_KEY=7d0X4l7ZJPCoD1qHVp35u-AwevhjVW0CiSMuWx9waBM=

  users_service:
    build: ./user_service
    ports:
      - "8084:5004"
    restart: always
    networks:
      - micros-net
    depends_on:
      - db_services
      - pulsar
      - create_namespace_topic
      
    environment:
      - ENCRYPTION_KEY=7d0X4l7ZJPCoD1qHVp35u-AwevhjVW0CiSMuWx9waBM=

  notifications_service:
    build: ./notifications_service
    ports:
      - "8086:5006"
    networks:
      - micros-net
    depends_on:
      - pulsar
      - create_namespace_topic
      - db_services
    environment:
      - PULSAR_URL=pulsar://pulsar:6650

      # Credenciales Mailjet (reemplaza con tus keys reales):
      - MJ_APIKEY_PUBLIC=8233f356a53b1981eb40b8dcb9b0d253
      - MJ_APIKEY_PRIVATE=9887974ee043a7333a7f472f36f51a21
      - MAILJET_DEFAULT_SENDER=fangeruno@gmail.com

    restart: always


networks:
  micros-net:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  pulsar_data:
