version: '3.8'
services:
  auth_service:
    build: ./auth_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/users_db

  certificator_service:
    build: ./certificator_service
    ports:
      - "5002:5002"

  item_valor_service:
    build: ./item_valor_service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/users_db

  user_service:
    build: ./user_service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/users_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
